### ISSUE TITLE
Database seed

### ISSUE THREAD

**Issue by ddnexus** [benkoshy/pagy-rails#6]
In order to play with the calendar extra, we need a bigger number of records with a field with different dates that span over a few years.

Since they are movies we could add a `published_at` or something, and populate that time field with a random date between a start and an end arbitrary time. (i.e. it should not be a start of year/month/day ... something random)  

Notice that we should ensure that there will be a random number of entries per day, something like 0..3 or 0..6.

I wrote some simple randomizer for the mock collection [here](https://github.com/ddnexus/pagy/blob/b96a922bf78d291311874e897efbf066f42931d3/test/mock_helpers/collection.rb#L69-L80) that can give you an idea about what we may need.

**Comment by benkoshy** [comment]
@ddnexus implemented in [this commit on the calendar branch](https://github.com/benkoshy/pagy-rails/commit/4b882e6883cef914c3f5f2a90a9de8a64487bee1). 

Please confirm whether the implementation is not good and/or requires changes.

**Comment by benkoshy** [comment]
@ddnexus I have attempted a WIP implementation here: https://github.com/benkoshy/pagy-rails/commit/f8454810773170a06c1155d9f62070cb18bff562 please tell me where it needs rectification. 

Note:
- I did not hard code dates e.g. movies beginning in October/Nov. 
- I have not implemented a new field `published_at`
- I have found that the seeding is far too slow for my liking. If you are happy with the implementation I will come up with a means to speed up the seeding.

References: 
- https://github.com/benkoshy/pagy-rails/commit/4b882e6883cef914c3f5f2a90a9de8a64487bee1#commitcomment-60669685

**Comment by ddnexus** [comment]
See 9012758a901a421693423cb25ab211c3274564bd

I abandoned the idea of reviewed_at, because it is actually useless. It is just about 3 seconds on my laptop.
