### ISSUE TITLE
Docker env not supported anymore

### ISSUE THREAD

**Issue by ddnexus** [benkoshy/pagy-rails#8]
For upgrade reference: https://github.com/benkoshy/pagy-rails/blob/master/pagy-rails-docker/README.md

**Comment by benkoshy** [comment]
Cool.  Will update

**Comment by benkoshy** [comment]
Closed with [4422464316d9aef262a13ceb8ea975090ee5e10a](https://github.com/benkoshy/pagy-rails/commit/4422464316d9aef262a13ceb8ea975090ee5e10a)

Thank you for reporting.
